Feat 1085: Dockerfile to support multiple architectures
ipfs/ipfs-cluster pull request #1196
Opened 2020-07-22 16:02 UTC by omkarprabhu-98

#1085 

Changes: 
- Downloads appropriate tini binary based on the machine architecture https://github.com/ipfs/go-ipfs/pull/7187
- Builds a static su-exec binary to make it robust (no dependency on libraries) and cross-platform support https://github.com/ipfs/go-ipfs/pull/7505

For uploading images with different machine architectures to DockerHub, [Buildx](https://docs.docker.com/buildx/working-with-buildx/) or some other tool may be required

Any suggestions on how to test this for architectures other than amd64? 
Other libraries required would have to be imported as shown here  https://github.com/ipfs/go-ipfs/pull/6854

2020-07-23 11:19 UTC, hsanjuan commented
> Any suggestions on how to test this for architectures other than amd64?

Maybe I can test in a raspberry Pi. Change looks OK, will leave unmerged until I can test it.

2020-08-31 14:54 UTC, Jorropo requested changes
Can you rebase on master pls ?
Also this :
https://github.com/ipfs/ipfs-cluster/blob/3ef09eec8f33bb0606a6c96e3b16da4c735df5c9/Dockerfile-test#L54
Need to be changed, `x86_64-linux-gnu` has to be changed depending of the configuration.

2020-09-01 17:30 UTC, omkarprabhu-98 commented
@Jorropo please take a look now

2020-09-01 18:03 UTC, Jorropo commented
> @Jorropo please take a look now

@omkarprabhu-98 error like this on an arm64 manjaro:
```
Step 36/40 : RUN mkdir -p $IPFS_CLUSTER_PATH &&     chown 1000:100 $IPFS_CLUSTER_PATH
 ---> Running in 3951667724d7
standard_init_linux.go:219: exec user process caused: exec format error
The command '/bin/sh -c mkdir -p $IPFS_CLUSTER_PATH &&     chown 1000:100 $IPFS_CLUSTER_PATH' returned a non-zero code: 1
make: *** [Makefile:62 : docker] Erreur 1
```
I'll maybe dig it later.

2020-09-01 18:44 UTC, Jorropo commented
@omkarprabhu-98 I've found the issue, we are pulling the `ipfs/go-ipfs:master` images :
https://github.com/ipfs/ipfs-cluster/blob/3ef09eec8f33bb0606a6c96e3b16da4c735df5c9/Dockerfile-test#L23
But IPFS doesn't support ARM docker build : you would need to fix ipfs/go-ipfs#7541 and pull the right image to work.
PS: You could also rebuild go-ipfs here but why not doing this in the go-ipfs repo (plus this would be awsome at the same time) ? Plus this will very likely get merged in the go-ipfs repo (see the help wanted tag in the issue).

2020-09-01 18:49 UTC, Jorropo commented
If you want some more insight about what to do check this :
https://github.com/ipfs/go-ipfs/issues/7541#issuecomment-661209028
Basicaly the docker hub image is built using the build made on circle CI host machine (amd64) :
https://github.com/ipfs/go-ipfs/blob/480defab689610550ee3d346e31441a2bb881fcb/.circleci/config.yml#L320

2020-09-02 09:45 UTC, hsanjuan commented
Note that `Dockefile-test` is not really useful to anyone anymore. If that's the blocker, it can be fully ignore (we definitely don't need to worry about arm builds for this one).

2020-09-02 10:00 UTC, Jorropo approved these changes
> Note that `Dockefile-test` is not really useful to anyone anymore. If that's the blocker, it can be fully ignore (we definitely don't need to worry about arm builds for this one).

@hsanjuan 
In this case it works on my arm64 manjaro, LGTM.

2021-01-13 20:05 UTC, merged