Deprecate secio to noise.
ipfs/ipfs-cluster pull request #1227
Opened 2020-08-28 21:04 UTC by Jorropo

Closes #1214

2020-08-28 21:05 UTC, Jorropo commented
/cc @hsanjuan

2020-08-29 08:49 UTC, Jorropo commented
@hsanjuan this should also fix the docker build (it was calling an non existent image).

2020-08-30 11:47 UTC, hsanjuan requested changes
Small ask. Thanks for contributing this!

2020-08-30 11:47 UTC, hsanjuan commented on clusterhost.go
> +		libp2p.Security(noise.ID, noise.New),
Noise should be first (move before tls).

2020-08-30 12:17 UTC, Jorropo commented
@hsanjuan done

2020-08-30 18:12 UTC, hsanjuan commented
@Jorropo it seems docker is still borked

2020-08-31 00:02 UTC, Jorropo commented
@hsanjuan it works now (on my machine at least) :)

2020-08-31 00:55 UTC, Jorropo commented
It finally builds !

2020-08-31 09:11 UTC, hsanjuan approved these changes

2020-08-31 09:12 UTC, merged